[project]
name = "supreme-bassoon"
version = "0.1.0"
description = "Basic interpolation"
authors = [{name = "Kirill Madorskii",email = "madorskii.kv@gmail.com"}]
readme = "README.md"

requires-python = ">=3.13"

dependencies = [
    "numpy (>=2.2.3,<3.0.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "scikit-image (>=0.25.2,<0.26.0)",
    "click (>=8.1.8,<9.0.0)",
    "requests (>=2.32.3,<3.0.0)",
]

[project.scripts]
console-test = "supreme_bassoon.console:main"
visualize    = "supreme_bassoon.visualize:main"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
